import { Competition, GroupFull, User } from "@/types";

// --- Mock data ---
const mockUser: User = {
  id: 1,
  username: "johnwick",
  email: "john@example.com",
  passwordHash: "hashed_password",
  firstName: "John",
  lastName: "Wick",
  createdAt: new Date().toISOString(),
};

const mockCompetition: Competition = {
  id: 1,
  themeId: 1,
  name: "Premier League",
  startDate: new Date().toISOString(),
  endDate: new Date(Date.now() + 7 * 86400000).toISOString(),
  status: "upcoming",
  createdAt: new Date().toISOString(),
};
export const mockGroups: GroupFull[] = [
  {
    id: 1,
    name: "HockerBet Champions",
    description: "Pariez et défiez vos amis sur vos équipes favorites !",
    ownerId: 1,
    competitionId: 1,
    visibility: "public",
    createdAt: new Date().toISOString(),
    owner: mockUser,
    competition: mockCompetition,
    members: [
      {
        id: 1,
        groupId: 1,
        userId: 1,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 12,
        user: mockUser,
      },
      {
        id: 2,
        groupId: 1,
        userId: 2,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 8,
        user: {
          id: 2,
          username: "Bob",
          email: "bob@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 1,
        groupId: 1,
        ruleDescription: "Exact Score",
        points: 5,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
      {
        id: 2,
        groupId: 1,
        ruleDescription: "Correct Winner",
        points: 2,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
    ],
    rankings: [
      {
        id: 1,
        groupId: 1,
        userId: 1,
        totalPoints: 12,
        totalPredictions: 5,
        correctPredictions: 3,
        rank: 1,
        user: mockUser,
      },
      {
        id: 2,
        groupId: 1,
        userId: 2,
        totalPoints: 8,
        totalPredictions: 5,
        correctPredictions: 2,
        rank: 2,
        user: {
          id: 2,
          username: "Bob",
          email: "bob@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 2,
    name: "Liga Legends",
    description: "Le meilleur groupe pour les fans de La Liga.",
    ownerId: 2,
    competitionId: 1,
    visibility: "private",
    createdAt: new Date().toISOString(),
    owner: {
      id: 2,
      username: "Bob",
      email: "bob@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 3,
        groupId: 2,
        userId: 2,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 20,
        user: {
          id: 2,
          username: "Bob",
          email: "bob@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 4,
        groupId: 2,
        userId: 3,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 17,
        user: {
          id: 3,
          username: "Carla",
          email: "carla@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 3,
        groupId: 2,
        ruleDescription: "Score exact",
        points: 5,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
      {
        id: 4,
        groupId: 2,
        ruleDescription: "Bonne équipe gagnante",
        points: 3,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
    ],
    rankings: [
      {
        id: 3,
        groupId: 2,
        userId: 2,
        totalPoints: 20,
        totalPredictions: 8,
        correctPredictions: 5,
        rank: 1,
        user: {
          id: 2,
          username: "Bob",
          email: "bob@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 4,
        groupId: 2,
        userId: 3,
        totalPoints: 17,
        totalPredictions: 8,
        correctPredictions: 4,
        rank: 2,
        user: {
          id: 3,
          username: "Carla",
          email: "carla@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 3,
    name: "Bet Masters",
    description: "Les stratèges des paris sportifs !",
    ownerId: 3,
    competitionId: 1,
    visibility: "public",
    createdAt: new Date().toISOString(),
    owner: {
      id: 3,
      username: "Carla",
      email: "carla@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 5,
        groupId: 3,
        userId: 3,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 15,
        user: {
          id: 3,
          username: "Carla",
          email: "carla@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 6,
        groupId: 3,
        userId: 4,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 10,
        user: {
          id: 4,
          username: "David",
          email: "david@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 5,
        groupId: 3,
        ruleDescription: "Score exact",
        points: 4,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
      {
        id: 6,
        groupId: 3,
        ruleDescription: "Bonne équipe gagnante",
        points: 2,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
    ],
    rankings: [
      {
        id: 5,
        groupId: 3,
        userId: 3,
        totalPoints: 15,
        totalPredictions: 6,
        correctPredictions: 3,
        rank: 1,
        user: {
          id: 3,
          username: "Carla",
          email: "carla@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 6,
        groupId: 3,
        userId: 4,
        totalPoints: 10,
        totalPredictions: 6,
        correctPredictions: 2,
        rank: 2,
        user: {
          id: 4,
          username: "David",
          email: "david@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 4,
    name: "Serie A Squad",
    description: "Fans de Milan, Roma et Napoli réunis ici.",
    ownerId: 4,
    competitionId: 1,
    visibility: "public",
    createdAt: new Date().toISOString(),
    owner: {
      id: 4,
      username: "David",
      email: "david@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 7,
        groupId: 4,
        userId: 4,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 22,
        user: {
          id: 4,
          username: "David",
          email: "david@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 8,
        groupId: 4,
        userId: 5,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 18,
        user: {
          id: 5,
          username: "Emma",
          email: "emma@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 7,
        groupId: 4,
        ruleDescription: "Score exact",
        points: 5,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
      {
        id: 8,
        groupId: 4,
        ruleDescription: "Bon vainqueur",
        points: 3,
        createdAt: new Date().toISOString(),
        ruleType: "EXACT_SCORE",
      },
    ],
    rankings: [
      {
        id: 7,
        groupId: 4,
        userId: 4,
        totalPoints: 22,
        totalPredictions: 10,
        correctPredictions: 6,
        rank: 1,
        user: {
          id: 4,
          username: "David",
          email: "david@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 8,
        groupId: 4,
        userId: 5,
        totalPoints: 18,
        totalPredictions: 10,
        correctPredictions: 5,
        rank: 2,
        user: {
          id: 5,
          username: "Emma",
          email: "emma@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 5,
    name: "Bundesliga Battle",
    description: "Pour les fans de Bayern et Dortmund.",
    ownerId: 5,
    competitionId: 1,
    visibility: "private",
    createdAt: new Date().toISOString(),
    owner: {
      id: 5,
      username: "Emma",
      email: "emma@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 9,
        groupId: 5,
        userId: 5,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 16,
        user: {
          id: 5,
          username: "Emma",
          email: "emma@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 10,
        groupId: 5,
        userId: 6,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 12,
        user: {
          id: 6,
          username: "Fred",
          email: "fred@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 9,
        groupId: 5,
        ruleDescription: "Score exact",
        points: 5,
        createdAt: new Date().toISOString(),
        ruleType: "BOTH_TEAMS_SCORE",
      },
    ],
    rankings: [
      {
        id: 9,
        groupId: 5,
        userId: 5,
        totalPoints: 16,
        totalPredictions: 5,
        correctPredictions: 3,
        rank: 1,
        user: {
          id: 5,
          username: "Emma",
          email: "emma@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 10,
        groupId: 5,
        userId: 6,
        totalPoints: 12,
        totalPredictions: 5,
        correctPredictions: 2,
        rank: 2,
        user: {
          id: 6,
          username: "Fred",
          email: "fred@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 6,
    name: "World Cup Fever",
    description: "Tous les passionnés du mondial !",
    ownerId: 6,
    competitionId: 1,
    visibility: "public",
    createdAt: new Date().toISOString(),
    owner: {
      id: 6,
      username: "Fred",
      email: "fred@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 11,
        groupId: 6,
        userId: 6,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 14,
        user: {
          id: 6,
          username: "Fred",
          email: "fred@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 12,
        groupId: 6,
        userId: 7,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 10,
        user: {
          id: 7,
          username: "Gina",
          email: "gina@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 10,
        groupId: 6,
        ruleDescription: "Correct score",
        points: 4,
        createdAt: new Date().toISOString(),
        ruleType: "CORRECT_DRAW",
      },
      {
        id: 11,
        groupId: 6,
        ruleDescription: "Winner",
        points: 2,
        createdAt: new Date().toISOString(),
        ruleType: "CORRECT_WINNER",
      },
    ],
    rankings: [
      {
        id: 11,
        groupId: 6,
        userId: 6,
        totalPoints: 14,
        totalPredictions: 5,
        correctPredictions: 3,
        rank: 1,
        user: {
          id: 6,
          username: "Fred",
          email: "fred@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 12,
        groupId: 6,
        userId: 7,
        totalPoints: 10,
        totalPredictions: 5,
        correctPredictions: 2,
        rank: 2,
        user: {
          id: 7,
          username: "Gina",
          email: "gina@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 7,
    name: "Euro Stars",
    description: "Préparez-vous pour l’Euro 2025 !",
    ownerId: 7,
    competitionId: 1,
    visibility: "public",
    createdAt: new Date().toISOString(),
    owner: {
      id: 7,
      username: "Gina",
      email: "gina@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 13,
        groupId: 7,
        userId: 7,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 19,
        user: {
          id: 7,
          username: "Gina",
          email: "gina@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 14,
        groupId: 7,
        userId: 8,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 14,
        user: {
          id: 8,
          username: "Henry",
          email: "henry@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
    scoringRules: [
      {
        id: 12,
        groupId: 7,
        ruleDescription: "Score exact",
        points: 5,
        createdAt: new Date().toISOString(),
        ruleType: "CORRECT_DRAW",
      },
      {
        id: 13,
        groupId: 7,
        ruleDescription: "Bon vainqueur",
        points: 3,
        createdAt: new Date().toISOString(),
        ruleType: "CORRECT_DRAW",
      },
    ],
    rankings: [
      {
        id: 13,
        groupId: 7,
        userId: 7,
        totalPoints: 19,
        totalPredictions: 6,
        correctPredictions: 4,
        rank: 1,
        user: {
          id: 7,
          username: "Gina",
          email: "gina@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 14,
        groupId: 7,
        userId: 8,
        totalPoints: 14,
        totalPredictions: 6,
        correctPredictions: 3,
        rank: 2,
        user: {
          id: 8,
          username: "Henry",
          email: "henry@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
    ],
  },
  {
    id: 8,
    name: "MLS Madness",
    description: "Pour les amateurs de foot américain !",
    ownerId: 8,
    competitionId: 1,
    visibility: "private",
    createdAt: new Date().toISOString(),
    owner: {
      id: 8,
      username: "Henry",
      email: "henry@example.com",
      passwordHash: "hashed",
      createdAt: new Date().toISOString(),
    },
    competition: mockCompetition,
    members: [
      {
        id: 15,
        groupId: 8,
        userId: 8,
        role: "owner",
        joinedAt: new Date().toISOString(),
        totalPoints: 10,
        user: {
          id: 8,
          username: "Henry",
          email: "henry@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 16,
        groupId: 8,
        userId: 1,
        role: "member",
        joinedAt: new Date().toISOString(),
        totalPoints: 8,
        user: mockUser,
      },
    ],
    scoringRules: [
      {
        id: 14,
        groupId: 8,
        ruleDescription: "Score exact",
        points: 5,
        createdAt: new Date().toISOString(),
        ruleType: "CORRECT_DRAW",
      },
    ],
    rankings: [
      {
        id: 15,
        groupId: 8,
        userId: 8,
        totalPoints: 10,
        totalPredictions: 4,
        correctPredictions: 2,
        rank: 1,
        user: {
          id: 8,
          username: "Henry",
          email: "henry@example.com",
          passwordHash: "hashed",
          createdAt: new Date().toISOString(),
        },
      },
      {
        id: 16,
        groupId: 8,
        userId: 1,
        totalPoints: 8,
        totalPredictions: 4,
        correctPredictions: 1,
        rank: 2,
        user: mockUser,
      },
    ],
  },
];
